### ISSUE TITLE
where is resource-switchtxt?

### ISSUE THREAD

**Issue by l-x007** [824728350/FlexPlan#1]
I am trying to understand this paper. When I ran the program, I found that there was no resource-switch file. Where can I find this file?

**Comment by l-x007** [comment]
Could you please provide me with a sample file?

**Comment by 824728350** [comment]
Sorry for the late reply, can you articulate what is the `resource-switch` file you mentioned?  This repos is self contained, which means the demo can run without any external files, so we cannot reproduce your problem on our end.
